version: '3'
volumes:
  foodgram_data:
  static_foodgram:
  media_foodgram:

services:
  db_f:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data/

  backend:
    image: mariasvet/foodgram_backend
    env_file: .env
    restart: unless-stopped
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/app/media
    depends_on:
      - db_f

  frontend:
    image: mariasvet/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - 8001:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - static_foodgram:/staticfiles/
      - media_foodgram:/app/media/
    depends_on:
      - backend
