version: '3'
volumes:
  foodgram_data:
  static_foodgram:
  media_foodgram:

services:
  db_f:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data

  backend:
    image: mariasvet/foodgram_backend
    env_file: .env
    restart: unless-stopped
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/app/media
    depends_on:
      - db_f

  frontend:
    image: mariasvet/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/
      - static_foodgram:/static

  gateway:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - static_foodgram:/staticfiles/
      - media_foodgram:/media/
    depends_on:
      - backend
      - frontend
