version: '3.3'
volumes:
  foodgram_data:
  static_foodgram:
  media_foodgram:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data/

  backend:
    image: mariasvet/foodgram_backend
    env_file: .env
    restart: unless-stopped
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/app/media
    depends_on:
      - db

  frontend:
    image: mariasvet/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
      - static_foodgram:/frontend_static

  nginx:
    image: mariasvet/foodgram_gateway
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - static_foodgram:/staticfiles/
      - media_foodgram:/app/media/
    depends_on:
      - backend
