# Generated by Django 3.2 on 2023-12-28 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['id'], 'verbose_name': 'Избраннный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id'], 'verbose_name': 'Ингредиент'},
        ),
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ['id'], 'verbose_name': 'Ингредиент в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['id'], 'verbose_name': 'Рецепт в листе покупок', 'verbose_name_plural': 'Рецепты в листе покупок'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': 'Тег'},
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='min amount is 1!'), django.core.validators.MaxValueValidator(32000, message='max amount is 32000')], verbose_name='Количество ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='min time is 1!'), django.core.validators.MaxValueValidator(3200, message='max time is 3200')], verbose_name='Время приготовления'),
        ),
    ]
