# Generated by Django 3.2 on 2023-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20231228_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(db_index=False, max_length=200, unique=True, verbose_name='Уникальный слаг'),
        ),
    ]
